"""initial schema

Revision ID: 45c73ceeec75
Revises:
Create Date: 2026-09-04 16:52:34.107822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c73ceeec75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'COMPLETED', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='confidencelevel'), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'EXTRACTED', 'SUPPORTED', 'CONTRADICTED', 'VERIFIED', name='evidencestatus'), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LOCATION', 'DATE', 'TIME', 'TEXT', 'NUMBER', 'URL', 'DOMAIN', 'EMAIL', 'PHONE', 'COORDINATE', 'VEHICLE_ID', 'BUILDING', 'LANDMARK', 'SIGN', 'OBJECT', 'ORGANIZATION', 'PERSON', 'OTHER', name='cluetype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('EXIF', 'OCR', 'VISUAL_ANALYSIS', 'FILENAME', 'USER_ADDED', 'EXTERNAL_SOURCE', name='cluesource'), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('EXTRACTED', 'UNVERIFIED', 'INVESTIGATING', 'SUPPORTED', 'CONTRADICTED', 'VERIFIED', name='cluestatus'), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('related_evidence_ids', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE_METADATA', 'OCR_TEXT', 'PUBLIC_SOURCE', 'MAP_INFORMATION', 'DOCUMENT', 'USER_OBSERVATION', 'TECHNICAL_ANALYSIS', name='evidencetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'EXTRACTED', 'SUPPORTED', 'CONTRADICTED', 'VERIFIED', name='evidencestatus'), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forensic_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('mime_validated', sa.Boolean(), nullable=True),
    sa.Column('magic_bytes_validated', sa.Boolean(), nullable=True),
    sa.Column('extension_match', sa.Boolean(), nullable=True),
    sa.Column('has_exif', sa.Boolean(), nullable=True),
    sa.Column('has_gps', sa.Boolean(), nullable=True),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('metadata_consistent', sa.Boolean(), nullable=True),
    sa.Column('timestamp_anomalies', sa.Text(), nullable=True),
    sa.Column('anomalies', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('image_hashes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sha512', sa.String(length=128), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_image_hashes_sha256'), 'image_hashes', ['sha256'], unique=False)
    op.create_table('image_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('camera_make', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('lens_model', sa.String(), nullable=True),
    sa.Column('software', sa.String(), nullable=True),
    sa.Column('datetime_original', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('gps_latitude', sa.String(), nullable=True),
    sa.Column('gps_longitude', sa.String(), nullable=True),
    sa.Column('gps_altitude', sa.String(), nullable=True),
    sa.Column('gps_timestamp', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('color_space', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('raw_exif', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('bounding_boxes', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('timestamp_source', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_events')
    op.drop_table('ocr_results')
    op.drop_table('image_metadata')
    op.drop_index(op.f('ix_image_hashes_sha256'), table_name='image_hashes')
    op.drop_table('image_hashes')
    op.drop_table('forensic_analyses')
    op.drop_table('evidence_items')
    op.drop_table('clues')
    op.drop_table('images')
    op.drop_table('findings')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
